version: "3"
services:
    webserver:
        container_name: proxy
        image: nginx:mainline-alpine
        ports:
        - 80:80
        - 443:443
        volumes:
        - ./nginx-conf/:/etc/nginx/conf.d
        - /etc/letsencrypt/:/etc/letsencrypt/
        depends_on:
            - api
        networks:
            - application-network
    api:
        container_name: sharerapi
        user: node
        build: .
        env_file: 
            - prod.env
        volumes: 
           - /home/administrator/keys:/usr/app/keys
        networks:
            - application-network
networks:
    application-network:
